Enable pip caching for GitHub Actions
psf/httpbin pull request #14
Opened 2023-08-13 02:22 UTC by mgorny

Enable pip caching in order to avoid repeatedly rebuilding all the PyPy wheels for source packages.  This is inspired by discussion in https://github.com/psf/requests/pull/6496 and it may help with the PyPy CI failures.

2023-08-13 03:15 UTC, mgorny commented
Ok, I think it works!

Notes:

1. It writes a new cache entry for every commit but I think it's fine, GH will simply have more purging to do.
2. It only works if action doesn't exceed timeout but if that happens at least once, the subsequent runs should be fast enough.
3. It's using deprecated method of setting build output — the new method doesn't work on Windows for some reason.

2023-08-13 15:50 UTC, mgorny commented
Switched to the new output variable method — it turned out that the example was wrong and `shell: bash` needs to be used. Filed https://github.com/actions/cache/issues/1220 for that.

2023-08-14 03:45 UTC, merged

2023-08-14 04:15 UTC, mgorny commented
Thanks! By the way, you may reconsider the `10m` timeout too, as that was the direct cause of PyPy failures before we sped it up.

2024-04-16 00:33 UTC, Mustafaalqaysy requested changes

2024-04-16 00:33 UTC, Mustafaalqaysy commented on .github/workflows/ci.yml
> +        echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
echo" dir=$50000 
(pip cache dir)" >s $GITHUB_oUTPUT

2024-04-16 00:33 UTC, Mustafaalqaysy approved these changes

2024-04-16 00:33 UTC, Mustafaalqaysy commented on .github/workflows/ci.yml
> +        echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
echo" dir=$50000 
(pip cache dir)" >s $GITHUB_oUTPUT